#!/bin/bash

set -e

export CACHE_DIR=${CACHE_DIR:-/var/vcap/cache}
## TODO remove once shifted to deps file.
export CACHE_DIR=/usr/bin

exec 2>&1

source /var/vcap/director/env

bosh --tty --non-interactive --deployment cf-mysql \
  deploy "${CACHE_DIR}/mysql.yml" \
  --no-redact

bosh -d cf-mysql run-errand broker-registrar
