// Code generated by MockGen. DO NOT EDIT.
// Source: code.cloudfoundry.org/cfdev/cmd/start (interfaces: Linuxkit)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockLinuxkit is a mock of Linuxkit interface
type MockLinuxkit struct {
	ctrl     *gomock.Controller
	recorder *MockLinuxkitMockRecorder
}

// MockLinuxkitMockRecorder is the mock recorder for MockLinuxkit
type MockLinuxkitMockRecorder struct {
	mock *MockLinuxkit
}

// NewMockLinuxkit creates a new mock instance
func NewMockLinuxkit(ctrl *gomock.Controller) *MockLinuxkit {
	mock := &MockLinuxkit{ctrl: ctrl}
	mock.recorder = &MockLinuxkitMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLinuxkit) EXPECT() *MockLinuxkitMockRecorder {
	return m.recorder
}

// Start mocks base method
func (m *MockLinuxkit) Start(arg0, arg1 int) error {
	ret := m.ctrl.Call(m, "Start", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start
func (mr *MockLinuxkitMockRecorder) Start(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockLinuxkit)(nil).Start), arg0, arg1)
}
