#!/usr/bin/env bash
set -euxo pipefail

cd "$(dirname "$0")/.."
rm -f output/*.*

echo "BUILD CF-DEPS.ISO"
./scripts/build-cf-deps-iso

echo "BUILD EFI IMAGE"
./scripts/build-image

pushd src/code.cloudfoundry.org/cfdev
  echo "BUILD CFDEV PLUGIN"
  ./generate-plugin.sh

  echo "INSTALL CFDEV PLUGIN"
  cf install-plugin -f cfdev
popd
