#!/usr/bin/env bash

set -ex

while getopts "c:b:" arg; do
  case $arg in
    c) cf_deps=$OPTARG
      ;;
    b) bosh_deps=$OPTARG
  esac
done

echo "$cf_deployment_releases"
stemcell_version=3541.4

if [[ "$cf_deps" = "" ]]; then
  echo "USAGE: ./build-cf-iso -c <path-to-compiled-cf-releases>"
  exit 1
fi

if [[ "$bosh_deps" = "" ]]; then
  echo "USAGE: ./build-cf-iso -c <path-to-compiled-cf-releases> -b <path-to-compiled-bosh-release>"
  exit 1
fi
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
output_dir="$script_dir/build"
iso_file="$output_dir"/cf-oss-deps.iso

rm -rf "$iso_file"
mkdir -p "$output_dir"
iso_dir="$(mktemp -d)"

"$script_dir"/../images/cf-oss/build.sh

# Place the 'workspace' container image
cid=$(docker run -d pivotal/cf-oss sleep infinity)
docker export "$cid" > "${iso_dir}/workspace.tar"
docker kill "$cid"
docker rm "$cid"

tar xzf "$cf_deps" -C $iso_dir --strip-components 1
tar xzf "$bosh_deps" -C $iso_dir --strip-components 1
mkisofs -V cf-oss-deps -R -o "$iso_file" "$iso_dir"
