#!/usr/bin/env bash
set -euxo pipefail

cd "$(dirname "$0")/.."
# TODO remove old files
mkdir -p output/cache/{bin,releases}

echo "GENERATE MANIFESTS"
./scripts/generate-bosh-manifest -b ../bosh-deployment/ 2> output/generate.log
./scripts/generate-cf-manifest -c ../cf-deployment/ 2> output/generate.log
./scripts/generate-cf-mysql-manifest -m ../cf-mysql-deployment/ 2> output/generate.log

## TODO "$script_dir"/../images/cf/build.sh (not sure why)
## TODO generate workspace.tar (from build-cf-deps-iso)

go run src/builder/main.go '3586.16' output/cache/*.yml
mkisofs -quiet -V cf-deps -R -o output/cf-deps.iso output/cache/
